### ISSUE TITLE
Bundling ruby really required?

### ISSUE THREAD

**Issue by dvonlehman** [lorennorman/ruby-on-lambda#1]
Nice, I've been meaning to look into doing just this to build Jekyll sites in Lambda. Curious why you decided to package up Ruby in your bundle rather than shelling out to the Ruby present on the Lambda image. According to the [Lambda FAQ](https://aws.amazon.com/lambda/faqs/): 

> Lambda functions can easily launch processes using languages supported by Amazon Linux, including Bash, Go, and Ruby

**Comment by lorennorman** [comment]
Oh man, that line sent me down the wrong path for days! As far as I can tell, Ruby isn't actually included in the Amazon Linux image used for Lambda. That line is aspirational, more like, "you can potentially do all of things things that we know work on Amazon Linux, but that doesn't mean we've set them up for you."

Would love to be proven wrong if you can track down the answer!

**Comment by dvonlehman** [comment]
Interesting, thanks for sharing your experiences. If I discover anything different I'll let you know.

**Comment by lorennorman** [comment]
Absolutely! That's the main reason I shared such a sparse project, so
little information out there. If I saved you those days: worth it!
