### ISSUE TITLE
How to return data from ruby script to node js

### ISSUE THREAD

**Issue by technolingo** [lorennorman/ruby-on-lambda#13]
I want to process some data using a ruby gem, how do I return the processed data back to handler.js?

**Comment by lorennorman** [comment]
That's up to you!

If you look at `index.js` you can see that it is already watching `stdout`, so you could just extend that:
https://github.com/lorennorman/ruby-on-lambda/blob/master/index.js#L9

Or you could write a file and read it from js, or whatever, sort of depends on your use case, how much data you're talking about, how heavily you're planning to process it in Node, etc.

Good luck!
