### ISSUE TITLE
error while trying to create to Gemfile.lock on lambda

### ISSUE THREAD

**Issue by iDiogenes** [lorennorman/ruby-on-lambda#3]
Great little wrapper for running ruby on lambda! 

I am able to run the ruby code fine as long as my Gemfile is empty. Once I add gems and deploy to lambda, on the lambda console I am presented with the following error:

```
/var/task/lib/ruby/lib/ruby/gems/2.2.0/gems/bundler-1.9.9/lib/bundler/definition.rb:252:in `rescue in lock': There was an error while trying to write to Gemfile.lock. It is likely that  (Bundler::InstallError)
you need to allow write permissions for the file at path: 
/var/task/lib/vendor/Gemfile.lock
    from /var/task/lib/ruby/lib/ruby/gems/2.2.0/gems/bundler-1.9.9/lib/bundler/definition.rb:237:in `lock'
    from /var/task/lib/ruby/lib/ruby/gems/2.2.0/gems/bundler-1.9.9/lib/bundler/environment.rb:34:in `lock'
    from /var/task/lib/ruby/lib/ruby/gems/2.2.0/gems/bundler-1.9.9/lib/bundler/runtime.rb:44:in `setup'
    from /var/task/lib/ruby/lib/ruby/gems/2.2.0/gems/bundler-1.9.9/lib/bundler.rb:122:in `setup'
    from /var/task/lib/ruby/lib/ruby/gems/2.2.0/gems/bundler-1.9.9/lib/bundler/setup.rb:18:in `<top (required)>'
    from /var/task/lib/ruby/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:128:in `require'
    from /var/task/lib/ruby/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:128:in `rescue in require'
    from /var/task/lib/ruby/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:39:in `require'
```

Any thoughts?

Thanks.

**Comment by lorennorman** [comment]
Looks like a permission issue on Gemfile.lock in the Lambda environment...
Why would it be writing to the lock at that time? You should have installed
the gems locally so that Gemfile.lock does not need to change once in the
environment...

...I think! I don't remember the ins and outs exactly. You may need to read
up on Traveling Ruby to get your head around this environment, it's a bit
tricky!

**Comment by iDiogenes** [comment]
I was able to get it working. I think the issue had to do with using a more recent version of bundler locally, than the bundler that comes with traveling ruby.

**Comment by lorennorman** [comment]
Congratulations! Now, whatcha gonna do with it?!?!?

**Comment by jlincoln** [comment]
iDiogenes.  If you are watching this.  I ran into the same issue and would like to know how to check the Bundler version that's on the Lambda server via Traveling Ruby.  I know I am using Bundler version 1.11.2.

Thank you

**Comment by iDiogenes** [comment]
Hey @jlincoln The version of bundler with Traveling ruby can be found here: https://github.com/phusion/traveling-ruby/blob/master/BUNDLER_VERSION.txt 

Created my Gemfile.lock with bundler 1.9.9 and it fixed the issue for me.

**Comment by lorennorman** [comment]
Is there anything I can add to the project to help with this issue? A note
in the readme or a default somewhere?

PRs are also welcome, of course!

**Comment by jlincoln** [comment]
Thank you very much.

I used "bundle _1.9.9_ install".

Jason
