### ISSUE TITLE
How to handle command line arguments?

### ISSUE THREAD

**Issue by oamike** [lorennorman/ruby-on-lambda#5]
We'd like to pass information from the event object to our ruby. We modified the index.js to include the necessary field:

```
  var child = spawn(invokeRubyApp, ["foo", event.Records[0].s3.object.key]);
```

But ARGV is always empty. 

```
puts "ARGV: #{ARGV}"
```

Outputs:

```
To: Lambda, 
From: Ruby! 
ARGV: []
```

We believe the call to spawn is correct, and we verified that event.Records[0].s3.object.key contains the key we need, but we can't figure out where the argument is getting lost.

**Comment by jlincoln** [comment]
Here is what I did and I am able to receive the event information in the app.rb.

index.js:
  var child = spawn(invokeRubyApp, [JSON.stringify(event, null, 2), JSON.stringify(context, null, 2)]);

app.rb:
  event = ARGV[0]
  context = ARGV[1]

**Comment by migalenkom** [comment]
#7 I have solution for this problem
[https://github.com/lorennorman/ruby-on-lambda/pull/7](url)

**Comment by migalenkom** [comment]
[https://github.com/lorennorman/ruby-on-lambda/pull/7](url)

**Comment by lorennorman** [comment]
Looks great, @migalenkom! :shipit:
